# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Eslint check
        # You may pin to the exact commit or the version.
        # uses: Krizzu/eslint-check-action@a10fa11628d6ba82cd67c76b5fb7d1549d55039e
        uses: Krizzu/eslint-check-action@v1.1.0
        with:
          # GitHub token
          ghToken: ${{ secrets.ESLINT_ACCESS_TOKEN }}
          # Relative path to files/directories to run lint on.
      - name: eslint + fix
      # You may pin to the exact commit or the version.
      # uses: getsentry/action-eslint-fix@18ace2d079e048d88f01cd6623b3f503d80bb487
        uses: getsentry/action-eslint-fix@v1
        with:
          # GitHub token
          GITHUB_TOKEN: ${{ secrets.ESLINT_ACCESS_TOKEN }}
